"""Generated from the original version4.py world.

Do not hand-edit existing records when checking fidelity.  Students can add
rooms and simple ``choices`` records directly; the engine fills in omitted
optional fields.
"""

WORLD_DATA = {'source_version': 'version4.py',
 'name': 'The Star Crystal',
 'start_location': 'village',
 'player': {'max_hp': 100,
            'attack_min': 6,
            'attack_max': 10,
            'defense': 1,
            'gold': 5,
            'inventory': [],
            'equipment': {'weapon': None, 'armor': None, 'charm': None},
            'flags': ['game_started']},
 'items': {'village_map': {'type': 'Item',
                           'item_id': 'village_map',
                           'name': 'Village Map',
                           'description': 'A hand-drawn map of the valley.',
                           'slot': None,
                           'power_bonus': 0,
                           'defense_bonus': 0,
                           'hp_bonus': 0,
                           'healing': 0,
                           'set_flags_on_pickup': [],
                           'tags': []},
           'moonleaf_herb': {'type': 'Item',
                             'item_id': 'moonleaf_herb',
                             'name': 'Moonleaf Herb',
                             'description': 'A silver-blue herb that smells sharp and fresh.',
                             'slot': None,
                             'power_bonus': 0,
                             'defense_bonus': 0,
                             'hp_bonus': 0,
                             'healing': 0,
                             'set_flags_on_pickup': [],
                             'tags': []},
           'rope': {'type': 'Item',
                    'item_id': 'rope',
                    'name': 'Rope',
                    'description': 'Strong rope left behind at an old campsite.',
                    'slot': None,
                    'power_bonus': 0,
                    'defense_bonus': 0,
                    'hp_bonus': 0,
                    'healing': 0,
                    'set_flags_on_pickup': [],
                    'tags': []},
           'lantern': {'type': 'Item',
                       'item_id': 'lantern',
                       'name': 'Lantern',
                       'description': 'A sturdy lantern. Essential in dark places.',
                       'slot': None,
                       'power_bonus': 0,
                       'defense_bonus': 0,
                       'hp_bonus': 0,
                       'healing': 0,
                       'set_flags_on_pickup': [],
                       'tags': []},
           'silver_key': {'type': 'Item',
                          'item_id': 'silver_key',
                          'name': 'Silver Key',
                          'description': 'A polished key shaped like a crescent moon.',
                          'slot': None,
                          'power_bonus': 0,
                          'defense_bonus': 0,
                          'hp_bonus': 0,
                          'healing': 0,
                          'set_flags_on_pickup': [],
                          'tags': []},
           'star_crystal': {'type': 'Item',
                            'item_id': 'star_crystal',
                            'name': 'Star Crystal',
                            'description': 'A warm crystal filled with light.',
                            'slot': None,
                            'power_bonus': 0,
                            'defense_bonus': 0,
                            'hp_bonus': 0,
                            'healing': 0,
                            'set_flags_on_pickup': ['has_star_crystal'],
                            'tags': []},
           'iron_sword': {'type': 'Item',
                          'item_id': 'iron_sword',
                          'name': 'Iron Sword',
                          'description': 'Rusty, but still dependable.',
                          'slot': 'weapon',
                          'power_bonus': 4,
                          'defense_bonus': 0,
                          'hp_bonus': 0,
                          'healing': 0,
                          'set_flags_on_pickup': [],
                          'tags': []},
           'guard_coat': {'type': 'Item',
                          'item_id': 'guard_coat',
                          'name': 'Guard Coat',
                          'description': 'Reinforced cloth armor.',
                          'slot': 'armor',
                          'power_bonus': 0,
                          'defense_bonus': 2,
                          'hp_bonus': 10,
                          'healing': 0,
                          'set_flags_on_pickup': [],
                          'tags': []},
           'lucky_coin': {'type': 'Item',
                          'item_id': 'lucky_coin',
                          'name': 'Lucky Coin',
                          'description': 'A coin etched with a star. It makes you strangely '
                                         'steady.',
                          'slot': 'charm',
                          'power_bonus': 0,
                          'defense_bonus': 1,
                          'hp_bonus': 0,
                          'healing': 0,
                          'set_flags_on_pickup': [],
                          'tags': []},
           'hunter_spear': {'type': 'Item',
                            'item_id': 'hunter_spear',
                            'name': 'Hunter Spear',
                            'description': 'A balanced spear made to keep biting creatures at a '
                                           'distance.',
                            'slot': 'weapon',
                            'power_bonus': 6,
                            'defense_bonus': 0,
                            'hp_bonus': 0,
                            'healing': 0,
                            'set_flags_on_pickup': [],
                            'tags': []},
           'health_tonic': {'type': 'Item',
                            'item_id': 'health_tonic',
                            'name': 'Health Tonic',
                            'description': 'A red tonic that restores health.',
                            'slot': None,
                            'power_bonus': 0,
                            'defense_bonus': 0,
                            'hp_bonus': 0,
                            'healing': 20,
                            'set_flags_on_pickup': [],
                            'tags': ['consumable']},
           'greater_tonic': {'type': 'Item',
                             'item_id': 'greater_tonic',
                             'name': 'Greater Tonic',
                             'description': 'A stronger restorative draught.',
                             'slot': None,
                             'power_bonus': 0,
                             'defense_bonus': 0,
                             'hp_bonus': 0,
                             'healing': 35,
                             'set_flags_on_pickup': [],
                             'tags': ['consumable']}},
 'rooms': {'village': {'key': 'village',
                       'name': 'Sunmeadow Village',
                       'description': 'A quiet village square surrounds a dry fountain. Traders, '
                                      'guards, and villagers drift across the square.',
                       'exits': [{'type': 'Exit',
                                  'direction': 'north',
                                  'destination': 'crossroads',
                                  'requires_item': None,
                                  'requires_flag': None,
                                  'blocked': False,
                                  'blocked_text': 'That path is blocked.',
                                  'warning_text': None,
                                  'on_attempt_effect': None,
                                  'on_blocked_effect': None,
                                  'on_success_effect': None}],
                       'items': [],
                       'npcs': [{'type': 'ElderNPC',
                                 'name': 'Elder Mira',
                                 'base_stats': {'type': 'Stats',
                                                'max_hp': 40,
                                                'attack_min': 4,
                                                'attack_max': 7,
                                                'defense': 0},
                                 'location': 'village',
                                 'health': 40,
                                 'gold': 0,
                                 'inventory': ['health_tonic'],
                                 'equipment': {'weapon': None, 'armor': None, 'charm': None},
                                 'description': 'The village elder watches the dry fountain with '
                                                'worried eyes.',
                                 'tags': [],
                                 'aggression': 5,
                                 'courage': 20,
                                 'willingness_to_trade': 15,
                                 'hostile': False,
                                 'dialogue_topics': [{'type': 'DialogueTopic',
                                                      'key': 'dry_fountain',
                                                      'title': 'Ask about the dry fountain',
                                                      'lines': ['Our fountain has run dry, and the '
                                                                "tower's shadow grows longer every "
                                                                'night.',
                                                                'Bring back the Star Crystal, and '
                                                                'Sunmeadow may shine again.'],
                                                      'required_flags': [],
                                                      'blocked_flags': ['quest_started'],
                                                      'required_items': [],
                                                      'once': True,
                                                      'outcome_effect': {'type': 'CompositeEffect',
                                                                         'effects': [{'type': 'GivePlayerItemEffect',
                                                                                      'item_ids': ['village_map']},
                                                                                     {'type': 'SetFlagEffect',
                                                                                      'flags': ['quest_started']}]}},
                                                     {'type': 'DialogueTopic',
                                                      'key': 'advice',
                                                      'title': 'Ask what to do next',
                                                      'lines': ['Listen to the valley. The people, '
                                                                'the ruins, and even the trees '
                                                                'know more than they first '
                                                                'reveal.'],
                                                      'required_flags': ['quest_started'],
                                                      'blocked_flags': ['game_won',
                                                                        'has_star_crystal'],
                                                      'required_items': [],
                                                      'once': False,
                                                      'outcome_effect': None},
                                                     {'type': 'DialogueTopic',
                                                      'key': 'return_crystal',
                                                      'title': 'Return the Star Crystal',
                                                      'lines': ['You found it... the Star Crystal!',
                                                                'You raise the crystal above the '
                                                                'fountain.',
                                                                'Light pours across the square. '
                                                                'Water bursts upward. Cheers echo '
                                                                'through the village.',
                                                                'You saved Sunmeadow Village. You '
                                                                'win!'],
                                                      'required_flags': ['has_star_crystal'],
                                                      'blocked_flags': ['game_won'],
                                                      'required_items': [],
                                                      'once': True,
                                                      'outcome_effect': {'type': 'SetFlagEffect',
                                                                         'flags': ['game_won']}}],
                                 'trade_offers': [],
                                 'riddle': None,
                                 'surrender_at_ratio': None,
                                 'surrender_lines': [],
                                 'surrender_trade_offers': [],
                                 'peaceful_after_surrender': True,
                                 'surrender_accept_lines': [],
                                 'surrender_reject_lines': [],
                                 'surrender_accept_effect': None,
                                 'defeat_lines': ['Elder Mira falls. The square goes silent.'],
                                 'reward_items': [],
                                 'reward_flags': [],
                                 'reward_gold': 0,
                                 'persistent': True,
                                 'used_topics': [],
                                 'completed_trades': [],
                                 'surrendered': False,
                                 'riddle_solved': False,
                                 'defeated': False},
                                {'type': 'GuardNPC',
                                 'name': 'Guard Halwen',
                                 'base_stats': {'type': 'Stats',
                                                'max_hp': 45,
                                                'attack_min': 6,
                                                'attack_max': 9,
                                                'defense': 2},
                                 'location': 'village',
                                 'health': 45,
                                 'gold': 12,
                                 'inventory': ['guard_coat', 'health_tonic'],
                                 'equipment': {'weapon': None,
                                               'armor': 'guard_coat',
                                               'charm': None},
                                 'description': 'A village guard in a faded coat watches the '
                                                'square with practiced patience.',
                                 'tags': ['guard', 'law'],
                                 'aggression': 40,
                                 'courage': 85,
                                 'willingness_to_trade': 0,
                                 'hostile': False,
                                 'dialogue_topics': [{'type': 'DialogueTopic',
                                                      'key': 'guard_law',
                                                      'title': 'Ask about the law',
                                                      'lines': ['Keep the peace, pay your debts, '
                                                                'and do not test my patience.',
                                                                'If you draw steel on the '
                                                                'innocent, I will answer it.'],
                                                      'required_flags': [],
                                                      'blocked_flags': [],
                                                      'required_items': [],
                                                      'once': False,
                                                      'outcome_effect': None}],
                                 'trade_offers': [],
                                 'riddle': None,
                                 'surrender_at_ratio': None,
                                 'surrender_lines': [],
                                 'surrender_trade_offers': [],
                                 'peaceful_after_surrender': True,
                                 'surrender_accept_lines': ['Drop your weapon and come quietly.',
                                                            'You can explain yourself from the '
                                                            'cell.'],
                                 'surrender_reject_lines': [],
                                 'surrender_accept_effect': {'type': 'CompositeEffect',
                                                             'effects': [{'type': 'SetFlagEffect',
                                                                          'flags': ['jailed']},
                                                                         {'type': 'MovePlayerEffect',
                                                                          'destination': 'jail',
                                                                          'text': 'Guard Halwen '
                                                                                  'binds your '
                                                                                  'hands and '
                                                                                  'marches you to '
                                                                                  'the village '
                                                                                  'jail.'}]},
                                 'defeat_lines': ['Guard Halwen crashes to the stones. A hush '
                                                  'spreads across the square.'],
                                 'reward_items': [],
                                 'reward_flags': [],
                                 'reward_gold': 0,
                                 'persistent': True,
                                 'used_topics': [],
                                 'completed_trades': [],
                                 'surrendered': False,
                                 'riddle_solved': False,
                                 'defeated': False},
                                {'type': 'MerchantNPC',
                                 'name': 'Merchant Sella',
                                 'base_stats': {'type': 'Stats',
                                                'max_hp': 35,
                                                'attack_min': 4,
                                                'attack_max': 6,
                                                'defense': 1},
                                 'location': 'village',
                                 'health': 35,
                                 'gold': 30,
                                 'inventory': ['hunter_spear', 'health_tonic', 'health_tonic'],
                                 'equipment': {'weapon': None, 'armor': None, 'charm': None},
                                 'description': 'A sharp-eyed merchant has laid out weapons, '
                                                'tonics, and travel gear on a thick canvas cloth.',
                                 'tags': [],
                                 'aggression': 10,
                                 'courage': 40,
                                 'willingness_to_trade': 90,
                                 'hostile': False,
                                 'dialogue_topics': [{'type': 'DialogueTopic',
                                                      'key': 'merchant_pitch',
                                                      'title': 'Ask what she recommends',
                                                      'lines': ['If you are heading for caves, buy '
                                                                'reach and buy confidence.',
                                                                'Spiders hate a spear point more '
                                                                'than a short blade.'],
                                                      'required_flags': [],
                                                      'blocked_flags': [],
                                                      'required_items': [],
                                                      'once': False,
                                                      'outcome_effect': None}],
                                 'trade_offers': [{'type': 'TradeOffer',
                                                   'title': 'Buy Hunter Spear for 12 gold',
                                                   'wants_items': [],
                                                   'gives_items': ['hunter_spear'],
                                                   'wants_gold': 12,
                                                   'gives_gold': 0,
                                                   'repeatable': False,
                                                   'required_flags': [],
                                                   'blocked_flags': []},
                                                  {'type': 'TradeOffer',
                                                   'title': 'Buy Health Tonic for 6 gold',
                                                   'wants_items': [],
                                                   'gives_items': ['health_tonic'],
                                                   'wants_gold': 6,
                                                   'gives_gold': 0,
                                                   'repeatable': True,
                                                   'required_flags': [],
                                                   'blocked_flags': []}],
                                 'riddle': None,
                                 'surrender_at_ratio': None,
                                 'surrender_lines': [],
                                 'surrender_trade_offers': [],
                                 'peaceful_after_surrender': True,
                                 'surrender_accept_lines': [],
                                 'surrender_reject_lines': [],
                                 'surrender_accept_effect': None,
                                 'defeat_lines': [],
                                 'reward_items': [],
                                 'reward_flags': [],
                                 'reward_gold': 0,
                                 'persistent': True,
                                 'used_topics': [],
                                 'completed_trades': [],
                                 'surrendered': False,
                                 'riddle_solved': False,
                                 'defeated': False}],
                       'features': [{'type': 'ScriptedFeature',
                                     'name': 'fountain',
                                     'verb': 'Rest at',
                                     'required_flags': [],
                                     'blocked_text': 'Nothing happens.',
                                     'once_flag': None,
                                     'first_effect': {'type': 'HealPlayerEffect',
                                                      'amount': 15,
                                                      'heal_text': 'You sit beside the fountain '
                                                                   'and catch your breath.',
                                                      'full_text': 'You already feel fully '
                                                                   'rested.'},
                                     'repeat_effect': None}],
                       'choices': []},
           'crossroads': {'key': 'crossroads',
                          'name': 'Old Crossroads',
                          'description': 'Four dirt paths meet under a leaning wooden sign.',
                          'exits': [{'type': 'Exit',
                                     'direction': 'south',
                                     'destination': 'village',
                                     'requires_item': None,
                                     'requires_flag': None,
                                     'blocked': False,
                                     'blocked_text': 'That path is blocked.',
                                     'warning_text': None,
                                     'on_attempt_effect': None,
                                     'on_blocked_effect': None,
                                     'on_success_effect': None},
                                    {'type': 'Exit',
                                     'direction': 'west',
                                     'destination': 'forest',
                                     'requires_item': None,
                                     'requires_flag': None,
                                     'blocked': False,
                                     'blocked_text': 'That path is blocked.',
                                     'warning_text': None,
                                     'on_attempt_effect': None,
                                     'on_blocked_effect': None,
                                     'on_success_effect': None},
                                    {'type': 'Exit',
                                     'direction': 'east',
                                     'destination': 'lake',
                                     'requires_item': None,
                                     'requires_flag': None,
                                     'blocked': False,
                                     'blocked_text': 'That path is blocked.',
                                     'warning_text': None,
                                     'on_attempt_effect': None,
                                     'on_blocked_effect': None,
                                     'on_success_effect': None},
                                    {'type': 'Exit',
                                     'direction': 'north',
                                     'destination': 'ruins',
                                     'requires_item': None,
                                     'requires_flag': None,
                                     'blocked': False,
                                     'blocked_text': 'That path is blocked.',
                                     'warning_text': None,
                                     'on_attempt_effect': None,
                                     'on_blocked_effect': None,
                                     'on_success_effect': {'type': 'ConditionalEffect',
                                                           'required_flags': [],
                                                           'blocked_flags': ['ruins_ambush_triggered'],
                                                           'required_items': [],
                                                           'success_effect': {'type': 'CompositeEffect',
                                                                              'effects': [{'type': 'PrintEffect',
                                                                                           'lines': ['As '
                                                                                                     'you '
                                                                                                     'head '
                                                                                                     'toward '
                                                                                                     'the '
                                                                                                     'ruins, '
                                                                                                     'a '
                                                                                                     'loose '
                                                                                                     'stone '
                                                                                                     'gives '
                                                                                                     'way '
                                                                                                     'underfoot '
                                                                                                     'and '
                                                                                                     'you '
                                                                                                     'stumble.']},
                                                                                          {'type': 'DamageCharacterEffect',
                                                                                           'target': 'player',
                                                                                           'amount': 4,
                                                                                           'text': None},
                                                                                          {'type': 'SetFlagEffect',
                                                                                           'flags': ['ruins_ambush_triggered']}]},
                                                           'failure_effect': None}}],
                          'items': [],
                          'npcs': [],
                          'features': [{'type': 'TextFeature',
                                        'name': 'wooden sign',
                                        'verb': 'Read',
                                        'text': 'NORTH -> Moonstone Ruins\n'
                                                'EAST  -> Mirror Lake\n'
                                                'WEST  -> Whispering Forest\n'
                                                'SOUTH -> Sunmeadow Village'}],
                          'choices': []},
           'forest': {'key': 'forest',
                      'name': 'Whispering Forest',
                      'description': 'Tall trees sway overhead. Moss, roots, and old camp supplies '
                                     'lie under the leaves.',
                      'exits': [{'type': 'Exit',
                                 'direction': 'east',
                                 'destination': 'crossroads',
                                 'requires_item': None,
                                 'requires_flag': None,
                                 'blocked': False,
                                 'blocked_text': 'That path is blocked.',
                                 'warning_text': None,
                                 'on_attempt_effect': None,
                                 'on_blocked_effect': None,
                                 'on_success_effect': None},
                                {'type': 'Exit',
                                 'direction': 'west',
                                 'destination': 'garden',
                                 'requires_item': None,
                                 'requires_flag': None,
                                 'blocked': False,
                                 'blocked_text': 'That path is blocked.',
                                 'warning_text': None,
                                 'on_attempt_effect': None,
                                 'on_blocked_effect': None,
                                 'on_success_effect': None},
                                {'type': 'Exit',
                                 'direction': 'north',
                                 'destination': 'cave_entrance',
                                 'requires_item': None,
                                 'requires_flag': None,
                                 'blocked': False,
                                 'blocked_text': 'That path is blocked.',
                                 'warning_text': 'The bramble path ahead looks painful. Push '
                                                 'through anyway?',
                                 'on_attempt_effect': None,
                                 'on_blocked_effect': None,
                                 'on_success_effect': {'type': 'ChanceEffect',
                                                       'chance': 0.6,
                                                       'success_effect': {'type': 'CompositeEffect',
                                                                          'effects': [{'type': 'PrintEffect',
                                                                                       'lines': ['Thorns '
                                                                                                 'rake '
                                                                                                 'your '
                                                                                                 'arms '
                                                                                                 'and '
                                                                                                 'tear '
                                                                                                 'at '
                                                                                                 'your '
                                                                                                 'clothes '
                                                                                                 'as '
                                                                                                 'you '
                                                                                                 'force '
                                                                                                 'your '
                                                                                                 'way '
                                                                                                 'through.']},
                                                                                      {'type': 'DamageCharacterEffect',
                                                                                       'target': 'player',
                                                                                       'amount': 6,
                                                                                       'text': None}]},
                                                       'failure_effect': {'type': 'PrintEffect',
                                                                          'lines': ['You find a '
                                                                                    'careful route '
                                                                                    'through the '
                                                                                    'brambles and '
                                                                                    'avoid the '
                                                                                    'worst of '
                                                                                    'them.']}}}],
                      'items': ['moonleaf_herb', 'rope', 'iron_sword', 'health_tonic'],
                      'npcs': [],
                      'features': [{'type': 'ScriptedFeature',
                                    'name': 'whispering trees',
                                    'verb': 'Listen to',
                                    'required_flags': [],
                                    'blocked_text': 'Nothing happens.',
                                    'once_flag': 'forest_hint_seen',
                                    'first_effect': {'type': 'PrintEffect',
                                                     'lines': ['A cool breeze seems to whisper: '
                                                               "'Light opens the dark path.'"]},
                                    'repeat_effect': {'type': 'PrintEffect',
                                                      'lines': ['The leaves rustle softly. The '
                                                                'forest has already shared its '
                                                                'hint.']}},
                                   {'type': 'ScriptedFeature',
                                    'name': 'unstable hillside',
                                    'verb': 'Climb',
                                    'required_flags': [],
                                    'blocked_text': 'Nothing happens.',
                                    'once_flag': 'landslide_happened',
                                    'first_effect': {'type': 'CompositeEffect',
                                                     'effects': [{'type': 'PrintEffect',
                                                                  'lines': ['You scramble up the '
                                                                            'unstable slope.',
                                                                            'A deep crack echoes '
                                                                            'through the trees.',
                                                                            'Rocks crash down and '
                                                                            'bury the garden '
                                                                            'trail!']},
                                                                 {'type': 'BlockPathEffect',
                                                                  'location_key': 'forest',
                                                                  'direction': 'west',
                                                                  'reason': 'A landslide has '
                                                                            'buried the trail '
                                                                            'under loose rocks.'},
                                                                 {'type': 'BlockPathEffect',
                                                                  'location_key': 'garden',
                                                                  'direction': 'east',
                                                                  'reason': 'A landslide has '
                                                                            'buried the trail '
                                                                            'under loose rocks.'}]},
                                    'repeat_effect': {'type': 'PrintEffect',
                                                      'lines': ['The hillside already collapsed. '
                                                                'Rocks still cover the trail.']}}],
                      'choices': []},
           'garden': {'key': 'garden',
                      'name': 'Hidden Garden',
                      'description': 'A secret clearing full of bright flowers and soft green '
                                     'light.',
                      'exits': [{'type': 'Exit',
                                 'direction': 'east',
                                 'destination': 'forest',
                                 'requires_item': None,
                                 'requires_flag': None,
                                 'blocked': False,
                                 'blocked_text': 'That path is blocked.',
                                 'warning_text': None,
                                 'on_attempt_effect': None,
                                 'on_blocked_effect': None,
                                 'on_success_effect': None}],
                      'items': [],
                      'npcs': [{'type': 'BanditNPC',
                                'name': 'Bandit Nox',
                                'base_stats': {'type': 'Stats',
                                               'max_hp': 28,
                                               'attack_min': 5,
                                               'attack_max': 9,
                                               'defense': 1},
                                'location': 'garden',
                                'health': 28,
                                'gold': 15,
                                'inventory': ['lucky_coin', 'greater_tonic', 'health_tonic'],
                                'equipment': {'weapon': 'iron_sword', 'armor': None, 'charm': None},
                                'description': 'A lean bandit lurks among the flowers, guarding a '
                                               'hidden stash.',
                                'tags': [],
                                'aggression': 70,
                                'courage': 35,
                                'willingness_to_trade': 10,
                                'hostile': False,
                                'dialogue_topics': [{'type': 'DialogueTopic',
                                                     'key': 'bandit_warning',
                                                     'title': 'Ask why he is here',
                                                     'lines': ['Because hidden places collect '
                                                               'hidden things.',
                                                               'And hidden things can be sold.'],
                                                     'required_flags': [],
                                                     'blocked_flags': ['bandit_spared'],
                                                     'required_items': [],
                                                     'once': False,
                                                     'outcome_effect': None},
                                                    {'type': 'DialogueTopic',
                                                     'key': 'bandit_after_surrender',
                                                     'title': 'Ask what changed his mind',
                                                     'lines': ['Turns out survival is worth more '
                                                               'than pride.'],
                                                     'required_flags': ['bandit_spared'],
                                                     'blocked_flags': [],
                                                     'required_items': [],
                                                     'once': False,
                                                     'outcome_effect': None}],
                                'trade_offers': [],
                                'riddle': None,
                                'surrender_at_ratio': 0.25,
                                'surrender_lines': ['Wait! Enough! I do not want to die here.',
                                                    'If you spare me, we can make a deal.'],
                                'surrender_trade_offers': [{'type': 'TradeOffer',
                                                            'title': 'Trade Moonleaf Herb for '
                                                                     'Lucky Coin',
                                                            'wants_items': ['moonleaf_herb'],
                                                            'gives_items': ['lucky_coin'],
                                                            'wants_gold': 0,
                                                            'gives_gold': 0,
                                                            'repeatable': False,
                                                            'required_flags': [],
                                                            'blocked_flags': []},
                                                           {'type': 'TradeOffer',
                                                            'title': 'Trade Rope for Greater Tonic',
                                                            'wants_items': ['rope'],
                                                            'gives_items': ['greater_tonic'],
                                                            'wants_gold': 0,
                                                            'gives_gold': 0,
                                                            'repeatable': False,
                                                            'required_flags': [],
                                                            'blocked_flags': []}],
                                'peaceful_after_surrender': True,
                                'surrender_accept_lines': ['Fine. Take what you came for and let '
                                                           'me live.'],
                                'surrender_reject_lines': [],
                                'surrender_accept_effect': None,
                                'defeat_lines': ['Bandit Nox drops his bag and limps away through '
                                                 'the garden.'],
                                'reward_items': [],
                                'reward_flags': ['bandit_defeated'],
                                'reward_gold': 10,
                                'persistent': True,
                                'used_topics': [],
                                'completed_trades': [],
                                'surrendered': False,
                                'riddle_solved': False,
                                'defeated': False}],
                      'features': [],
                      'choices': []},
           'lake': {'key': 'lake',
                    'name': 'Mirror Lake',
                    'description': 'A glassy lake reflects the sky. A weathered fisherman waits by '
                                   'the dock.',
                    'exits': [{'type': 'Exit',
                               'direction': 'west',
                               'destination': 'crossroads',
                               'requires_item': None,
                               'requires_flag': None,
                               'blocked': False,
                               'blocked_text': 'That path is blocked.',
                               'warning_text': None,
                               'on_attempt_effect': None,
                               'on_blocked_effect': None,
                               'on_success_effect': None}],
                    'items': [],
                    'npcs': [{'type': 'MerchantNPC',
                              'name': 'Fisher Rowan',
                              'base_stats': {'type': 'Stats',
                                             'max_hp': 35,
                                             'attack_min': 4,
                                             'attack_max': 6,
                                             'defense': 1},
                              'location': 'lake',
                              'health': 35,
                              'gold': 8,
                              'inventory': ['lantern', 'guard_coat', 'health_tonic'],
                              'equipment': {'weapon': None, 'armor': 'guard_coat', 'charm': None},
                              'description': 'A patient fisherman sits on the dock, humming to '
                                             'himself.',
                              'tags': [],
                              'aggression': 10,
                              'courage': 40,
                              'willingness_to_trade': 90,
                              'hostile': False,
                              'dialogue_topics': [{'type': 'DialogueTopic',
                                                   'key': 'lake_gossip',
                                                   'title': 'Ask about the lake',
                                                   'lines': ['The lake tells you things if you '
                                                             'wait long enough.',
                                                             'Mostly warnings. Sometimes luck.'],
                                                   'required_flags': [],
                                                   'blocked_flags': [],
                                                   'required_items': [],
                                                   'once': False,
                                                   'outcome_effect': None},
                                                  {'type': 'DialogueTopic',
                                                   'key': 'ask_tower',
                                                   'title': 'Ask about the tower',
                                                   'lines': ['Dark places do not stay dark '
                                                             'forever. Sometimes they only wait '
                                                             'for the right light.'],
                                                   'required_flags': [],
                                                   'blocked_flags': [],
                                                   'required_items': [],
                                                   'once': False,
                                                   'outcome_effect': None}],
                              'trade_offers': [{'type': 'TradeOffer',
                                                'title': 'Trade Moonleaf Herb for Lantern',
                                                'wants_items': ['moonleaf_herb'],
                                                'gives_items': ['lantern'],
                                                'wants_gold': 0,
                                                'gives_gold': 0,
                                                'repeatable': False,
                                                'required_flags': [],
                                                'blocked_flags': []},
                                               {'type': 'TradeOffer',
                                                'title': 'Trade Lucky Coin for Guard Coat',
                                                'wants_items': ['lucky_coin'],
                                                'gives_items': ['guard_coat'],
                                                'wants_gold': 0,
                                                'gives_gold': 0,
                                                'repeatable': False,
                                                'required_flags': [],
                                                'blocked_flags': []}],
                              'riddle': None,
                              'surrender_at_ratio': None,
                              'surrender_lines': [],
                              'surrender_trade_offers': [],
                              'peaceful_after_surrender': True,
                              'surrender_accept_lines': [],
                              'surrender_reject_lines': [],
                              'surrender_accept_effect': None,
                              'defeat_lines': ['Fisher Rowan drops his rod and backs away from the '
                                               'dock.'],
                              'reward_items': [],
                              'reward_flags': [],
                              'reward_gold': 0,
                              'persistent': True,
                              'used_topics': [],
                              'completed_trades': [],
                              'surrendered': False,
                              'riddle_solved': False,
                              'defeated': False}],
                    'features': [],
                    'choices': []},
           'cave_entrance': {'key': 'cave_entrance',
                             'name': 'Cave Entrance',
                             'description': 'A crack in the hillside opens into darkness. Cold air '
                                            'spills out.',
                             'exits': [{'type': 'Exit',
                                        'direction': 'south',
                                        'destination': 'forest',
                                        'requires_item': None,
                                        'requires_flag': None,
                                        'blocked': False,
                                        'blocked_text': 'That path is blocked.',
                                        'warning_text': None,
                                        'on_attempt_effect': None,
                                        'on_blocked_effect': None,
                                        'on_success_effect': None},
                                       {'type': 'Exit',
                                        'direction': 'north',
                                        'destination': 'cave_depths',
                                        'requires_item': 'lantern',
                                        'requires_flag': None,
                                        'blocked': False,
                                        'blocked_text': 'It is too dark to enter safely. You need '
                                                        'a Lantern.',
                                        'warning_text': None,
                                        'on_attempt_effect': None,
                                        'on_blocked_effect': {'type': 'PrintEffect',
                                                              'lines': ['Shadows shift in the '
                                                                        'crack ahead. You '
                                                                        'reconsider.']},
                                        'on_success_effect': None}],
                             'items': [],
                             'npcs': [],
                             'features': [],
                             'choices': []},
           'cave_depths': {'key': 'cave_depths',
                           'name': 'Crystal Cave',
                           'description': 'Blue crystals glow faintly from the cave walls.',
                           'exits': [{'type': 'Exit',
                                      'direction': 'south',
                                      'destination': 'cave_entrance',
                                      'requires_item': None,
                                      'requires_flag': None,
                                      'blocked': False,
                                      'blocked_text': 'That path is blocked.',
                                      'warning_text': None,
                                      'on_attempt_effect': None,
                                      'on_blocked_effect': None,
                                      'on_success_effect': None}],
                           'items': [],
                           'npcs': [{'type': 'NPC',
                                     'name': 'Crystal Spider',
                                     'base_stats': {'type': 'Stats',
                                                    'max_hp': 24,
                                                    'attack_min': 5,
                                                    'attack_max': 8,
                                                    'defense': 2},
                                     'location': 'cave_depths',
                                     'health': 24,
                                     'gold': 0,
                                     'inventory': ['silver_key', 'health_tonic'],
                                     'equipment': {'weapon': None, 'armor': None, 'charm': None},
                                     'description': 'A giant spider clings to a web of glowing '
                                                    'crystal threads.',
                                     'tags': ['monster'],
                                     'aggression': 90,
                                     'courage': 100,
                                     'willingness_to_trade': 0,
                                     'hostile': False,
                                     'dialogue_topics': [],
                                     'trade_offers': [],
                                     'riddle': None,
                                     'surrender_at_ratio': None,
                                     'surrender_lines': [],
                                     'surrender_trade_offers': [],
                                     'peaceful_after_surrender': True,
                                     'surrender_accept_lines': [],
                                     'surrender_reject_lines': ['The spider only clicks its '
                                                                'mandibles and closes in.'],
                                     'surrender_accept_effect': None,
                                     'defeat_lines': ['The Crystal Spider curls up and stops '
                                                      'moving.'],
                                     'reward_items': [],
                                     'reward_flags': ['spider_defeated'],
                                     'reward_gold': 14,
                                     'persistent': True,
                                     'used_topics': [],
                                     'completed_trades': [],
                                     'surrendered': False,
                                     'riddle_solved': False,
                                     'defeated': False}],
                           'features': [{'type': 'TextFeature',
                                         'name': 'glowing crystals',
                                         'verb': 'Study',
                                         'text': 'Their light feels ancient, calm, and strangely '
                                                 'familiar. You begin to suspect the tower and '
                                                 'village are connected by old magic.'}],
                           'choices': []},
           'ruins': {'key': 'ruins',
                     'name': 'Moonstone Ruins',
                     'description': 'Broken pillars and ancient arches rise from a hilltop.',
                     'exits': [{'type': 'Exit',
                                'direction': 'south',
                                'destination': 'crossroads',
                                'requires_item': None,
                                'requires_flag': None,
                                'blocked': False,
                                'blocked_text': 'That path is blocked.',
                                'warning_text': None,
                                'on_attempt_effect': None,
                                'on_blocked_effect': None,
                                'on_success_effect': None},
                               {'type': 'Exit',
                                'direction': 'north',
                                'destination': 'tower_gate',
                                'requires_item': 'rope',
                                'requires_flag': None,
                                'blocked': False,
                                'blocked_text': 'The path ahead is broken. You need a Rope to '
                                                'cross safely.',
                                'warning_text': 'The crossing is narrow and unstable. Go on?',
                                'on_attempt_effect': None,
                                'on_blocked_effect': {'type': 'PrintEffect',
                                                      'lines': ['The gap ahead looks fatal without '
                                                                'proper support.']},
                                'on_success_effect': {'type': 'ChanceEffect',
                                                      'chance': 0.3,
                                                      'success_effect': {'type': 'CompositeEffect',
                                                                         'effects': [{'type': 'PrintEffect',
                                                                                      'lines': ['The '
                                                                                                'old '
                                                                                                'crossing '
                                                                                                'gives '
                                                                                                'way '
                                                                                                'beneath '
                                                                                                'you '
                                                                                                'for '
                                                                                                'a '
                                                                                                'moment. '
                                                                                                'Your '
                                                                                                'pack '
                                                                                                'slams '
                                                                                                'against '
                                                                                                'the '
                                                                                                'stone.']},
                                                                                     {'type': 'DamageCharacterEffect',
                                                                                      'target': 'player',
                                                                                      'amount': 5,
                                                                                      'text': None},
                                                                                     {'type': 'ConditionalEffect',
                                                                                      'required_flags': [],
                                                                                      'blocked_flags': [],
                                                                                      'required_items': ['health_tonic'],
                                                                                      'success_effect': {'type': 'RemoveItemEffect',
                                                                                                         'item_id': 'health_tonic',
                                                                                                         'target': 'player',
                                                                                                         'text': 'One '
                                                                                                                 'of '
                                                                                                                 'your '
                                                                                                                 'Health '
                                                                                                                 'Tonics '
                                                                                                                 'shatters '
                                                                                                                 'on '
                                                                                                                 'the '
                                                                                                                 'rocks.'},
                                                                                      'failure_effect': None}]},
                                                      'failure_effect': {'type': 'PrintEffect',
                                                                         'lines': ['You cross the '
                                                                                   'broken path '
                                                                                   'without '
                                                                                   'incident.']}}}],
                     'items': [],
                     'npcs': [],
                     'features': [{'type': 'ScriptedFeature',
                                   'name': 'old winch',
                                   'verb': 'Turn',
                                   'required_flags': ['landslide_happened'],
                                   'blocked_text': 'The mechanism is tied to the collapsed trail, '
                                                   'but nothing needs clearing yet.',
                                   'once_flag': 'garden_path_reopened',
                                   'first_effect': {'type': 'CompositeEffect',
                                                    'effects': [{'type': 'PrintEffect',
                                                                 'lines': ['You turn the ancient '
                                                                           'winch.',
                                                                           'Some buried stones '
                                                                           'shift and part of the '
                                                                           'trail is cleared.']},
                                                                {'type': 'UnblockPathEffect',
                                                                 'location_key': 'forest',
                                                                 'direction': 'west'},
                                                                {'type': 'UnblockPathEffect',
                                                                 'location_key': 'garden',
                                                                 'direction': 'east'}]},
                                   'repeat_effect': {'type': 'PrintEffect',
                                                     'lines': ['The old winch has already done all '
                                                               'it can.']}}],
                     'choices': []},
           'tower_gate': {'key': 'tower_gate',
                          'name': 'Tower Gate',
                          'description': 'An iron gate blocks the tower stairs. The keyhole is '
                                         'shaped like a crescent moon.',
                          'exits': [{'type': 'Exit',
                                     'direction': 'south',
                                     'destination': 'ruins',
                                     'requires_item': None,
                                     'requires_flag': None,
                                     'blocked': False,
                                     'blocked_text': 'That path is blocked.',
                                     'warning_text': None,
                                     'on_attempt_effect': None,
                                     'on_blocked_effect': None,
                                     'on_success_effect': None},
                                    {'type': 'Exit',
                                     'direction': 'up',
                                     'destination': 'tower_top',
                                     'requires_item': 'silver_key',
                                     'requires_flag': None,
                                     'blocked': False,
                                     'blocked_text': 'The gate is locked. You need the Silver Key.',
                                     'warning_text': None,
                                     'on_attempt_effect': None,
                                     'on_blocked_effect': None,
                                     'on_success_effect': {'type': 'ConditionalEffect',
                                                           'required_flags': [],
                                                           'blocked_flags': ['tower_entry_event'],
                                                           'required_items': [],
                                                           'success_effect': {'type': 'CompositeEffect',
                                                                              'effects': [{'type': 'PrintEffect',
                                                                                           'lines': ['Ancient '
                                                                                                     'light '
                                                                                                     'flickers '
                                                                                                     'along '
                                                                                                     'the '
                                                                                                     'stairwell '
                                                                                                     'as '
                                                                                                     'the '
                                                                                                     'gate '
                                                                                                     'opens.']},
                                                                                          {'type': 'SetFlagEffect',
                                                                                           'flags': ['tower_entry_event']}]},
                                                           'failure_effect': None}}],
                          'items': [],
                          'npcs': [],
                          'features': [],
                          'choices': []},
           'tower_top': {'key': 'tower_top',
                         'name': 'Tower Summit',
                         'description': 'Wind curls around the broken top of the tower. A glowing '
                                        'crystal rests on a pedestal.',
                         'exits': [{'type': 'Exit',
                                    'direction': 'down',
                                    'destination': 'tower_gate',
                                    'requires_item': None,
                                    'requires_flag': None,
                                    'blocked': False,
                                    'blocked_text': 'That path is blocked.',
                                    'warning_text': None,
                                    'on_attempt_effect': None,
                                    'on_blocked_effect': None,
                                    'on_success_effect': None}],
                         'items': [],
                         'npcs': [{'type': 'GuardianNPC',
                                   'name': 'Tower Guardian',
                                   'base_stats': {'type': 'Stats',
                                                  'max_hp': 38,
                                                  'attack_min': 7,
                                                  'attack_max': 11,
                                                  'defense': 2},
                                   'location': 'tower_top',
                                   'health': 38,
                                   'gold': 0,
                                   'inventory': ['star_crystal'],
                                   'equipment': {'weapon': None, 'armor': None, 'charm': None},
                                   'description': 'A glowing spirit hovers beside the pedestal.',
                                   'tags': [],
                                   'aggression': 50,
                                   'courage': 90,
                                   'willingness_to_trade': 0,
                                   'hostile': False,
                                   'dialogue_topics': [{'type': 'DialogueTopic',
                                                        'key': 'guardian_warning',
                                                        'title': 'Ask who the crystal belongs to',
                                                        'lines': ['The crystal does not belong to '
                                                                  'one hand. It belongs to '
                                                                  'balance.'],
                                                        'required_flags': [],
                                                        'blocked_flags': ['guardian_passed'],
                                                        'required_items': [],
                                                        'once': False,
                                                        'outcome_effect': None},
                                                       {'type': 'DialogueTopic',
                                                        'key': 'guardian_after_trial',
                                                        'title': 'Ask if the trial is complete',
                                                        'lines': ['The trial is complete. The Star '
                                                                  'Crystal may now be taken.'],
                                                        'required_flags': ['guardian_passed'],
                                                        'blocked_flags': [],
                                                        'required_items': [],
                                                        'once': False,
                                                        'outcome_effect': None}],
                                   'trade_offers': [],
                                   'riddle': {'type': 'Riddle',
                                              'question': 'I am always running, but I never walk. '
                                                          'I often murmur, but I never talk. What '
                                                          'am I?',
                                              'answers': ['river', 'a river', 'stream', 'a stream'],
                                              'intro_lines': ['Answer my riddle, and the crystal '
                                                              'may be yours.'],
                                              'success_lines': ['Wisdom and patience walk beside '
                                                                'you. Step forward.'],
                                              'failure_lines': ['Not quite. Think more carefully.'],
                                              'repeat_lines': ['The trial is complete. The Star '
                                                               'Crystal may now be taken.'],
                                              'damage_on_failure': 12,
                                              'set_flags_on_success': ['guardian_passed']},
                                   'surrender_at_ratio': None,
                                   'surrender_lines': [],
                                   'surrender_trade_offers': [],
                                   'peaceful_after_surrender': True,
                                   'surrender_accept_lines': [],
                                   'surrender_reject_lines': ['The trial cannot be escaped. Only '
                                                              'answered or endured.'],
                                   'surrender_accept_effect': None,
                                   'defeat_lines': ['The guardian dissolves into drifting sparks '
                                                    'of light.'],
                                   'reward_items': [],
                                   'reward_flags': ['guardian_passed'],
                                   'reward_gold': 0,
                                   'persistent': True,
                                   'used_topics': [],
                                   'completed_trades': [],
                                   'surrendered': False,
                                   'riddle_solved': False,
                                   'defeated': False}],
                         'features': [],
                         'choices': []},
           'jail': {'key': 'jail',
                    'name': 'Village Jail',
                    'description': 'A cramped stone cell. The door is locked from the outside, and '
                                   'there is no key within reach.',
                    'exits': [],
                    'items': [],
                    'npcs': [],
                    'features': [{'type': 'ScriptedFeature',
                                  'name': 'prison cot',
                                  'verb': 'Serve time on',
                                  'required_flags': ['jailed'],
                                  'blocked_text': 'There is no sentence to serve right now.',
                                  'once_flag': None,
                                  'first_effect': {'type': 'CompositeEffect',
                                                   'effects': [{'type': 'PrintEffect',
                                                                'lines': ['You sit on the narrow '
                                                                          'cot and wait.',
                                                                          'Hours pass. Your anger '
                                                                          'cools. The guard '
                                                                          'finally opens the '
                                                                          'cell.']},
                                                               {'type': 'SetBountyEffect',
                                                                'amount': 0},
                                                               {'type': 'ClearFlagEffect',
                                                                'flags': ['jailed']},
                                                               {'type': 'MovePlayerEffect',
                                                                'destination': 'village',
                                                                'text': 'You are released back '
                                                                        'into Sunmeadow Village.'},
                                                               {'type': 'HealPlayerEffect',
                                                                'amount': 999,
                                                                'heal_text': "A night's rest mends "
                                                                             'your wounds.',
                                                                'full_text': 'You are already '
                                                                             'fully rested.'}]},
                                  'repeat_effect': None}],
                    'choices': []}},
 'encounters': [{'name': 'guard_confrontation',
                 'locations': ['village'],
                 'chance': 1.0,
                 'required_flags': [],
                 'blocked_flags': ['game_won', 'jailed'],
                 'once_flag': None,
                 'handler': 'handle_guard_confrontation',
                 'predicate': '<lambda>'},
                {'name': 'forest_small_spider',
                 'locations': ['forest'],
                 'chance': 0.3,
                 'required_flags': [],
                 'blocked_flags': ['jailed'],
                 'once_flag': None,
                 'handler': 'handle_forest_spider_encounter',
                 'predicate': '<lambda>'}]}

# ---------------------------------------------------------------------------
# STUDENT EXTENSION ZONE
# ---------------------------------------------------------------------------
# Add rooms here instead of editing the preserved original records above.
# A simple room needs only a name, description, exits, and optional choices.
# The engine treats omitted items, NPCs, and features as empty.
EXTRA_ROOMS = {}

# Add simple choices to an existing room without changing engine code. A
# choice can also move into one of your extra rooms. For example:
# EXTRA_ROOMS = {
#     "old_observatory": {
#         "name": "Old Observatory",
#         "description": "Dusty lenses point through a hole in the roof.",
#         "exits": [{"direction": "back", "destination": "crossroads"}],
#         "choices": [
#             {
#                 "text": "Look through the telescope",
#                 "result": ["A blue star flickers above the hills."],
#             },
#         ],
#     },
# }
# EXTRA_CHOICES = {
#     "crossroads": [
#         {"text": "Climb the hill to the old observatory", "go": "old_observatory"},
#     ],
# }
EXTRA_CHOICES = {}

WORLD_DATA["rooms"].update(EXTRA_ROOMS)
for _room_key, _choices in EXTRA_CHOICES.items():
    WORLD_DATA["rooms"][_room_key].setdefault("choices", []).extend(_choices)
